### ISSUE TITLE
Heroku build failed to compile Swift app

### ISSUE THREAD

**Issue by iberatkaya** [vapor-community/heroku-buildpack#54]
Hello. I am trying to deploy my first ever Vapor project to Heroku. Everything works fine on my local Mac computer, but when I try to deploy to Heroku I get the following error:

```
-----> Swift app detected
-----> Using Swift 5.3 (default)
-----> Using built-in clang (Swift 5.3)
-----> Installing swiftenv
-----> Installing Swift 5.3
..........
..........
..........
[868/869] Compiling Vapor Application.swift
[869/870] Compiling App ImageController.swift
/tmp/build_0b01c993/Sources/App/Controllers/ImageController/ImageController.swift:12:41: error: extraneous argument label 'data:' in call
    guard var image = Image<RGBA<UInt8>>(data: Data(buffer: params.file.data)) else {
                                        ^~~~~~~
                                         
/tmp/build_0b01c993/Sources/App/Controllers/ImageController/ImageController.swift:12:48: error: cannot convert value of type 'Data' to expected argument type 'ImageSlice<RGBA<UInt8>>'
    guard var image = Image<RGBA<UInt8>>(data: Data(buffer: params.file.data)) else {
                                               ^
 !     Push rejected, failed to compile Swift app.
 !     Push failed
```

It says that the project could not be compiled, but the project can compile and run without any issues on my Mac computer. It seems to complain about the package I use. I thought there might be a problem with the [SwiftImage](https://github.com/koher/swift-image) version, but changing its version did not solve my problem. I checked on Heroku's activity build logs to view which version of SwiftImage it was trying to use, and it correctly uses the same version in my Package.swift file:

```
Cloning https://github.com/koher/swift-image.git
Resolving https://github.com/koher/swift-image.git at 0.7.1
```

My Package.swift is like this:

```
// swift-tools-version:5.3
import PackageDescription

let package = Package(
    name: "imageEditor",
    platforms: [
       .macOS(.v10_15)
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "4.0.0"),
        .package(name: "SwiftImage", url: "https://github.com/koher/swift-image.git", .exact("0.7.1"))
    ],
    targets: [
        .target(
            name: "App",
            dependencies: [
                .product(name: "Vapor", package: "vapor"),
                .product(name: "SwiftImage", package: "SwiftImage")
            ],
            swiftSettings: [
                // Enable better optimizations when building in Release configuration. Despite the use of
                // the `.unsafeFlags` construct required by SwiftPM, this flag is recommended for Release
                // builds. See <https://github.com/swift-server/guides#building-for-production> for details.
                .unsafeFlags(["-cross-module-optimization"], .when(configuration: .release))
            ]
        ),
        .target(name: "Run", dependencies: [.target(name: "App")]),
        .testTarget(name: "AppTests", dependencies: [
            .target(name: "App"),
            .product(name: "XCTVapor", package: "vapor"),
        ])
    ]
)
```

**Comment by vzsg** [comment]
This is not related to Heroku or this buildpack, but the Linux compatibility of the mentioned SwiftImage package and by extension, your project.

It seems that the `Image(data:)` initializer that _your_ ImageController class is using is [declared with canImport guards](https://github.com/koher/swift-image/blob/master/Sources/SwiftImage/AppKit.swift#L33). And since the AppKit framework does not exist on Linux, neither will the initializer, explaining the error message you got.

You will need to find another way to load image data on Linux. You will be able to iterate faster if you first try to build your project with Docker (e.g. in a throwaway container) or a Linux VM. Once the project builds there, you can resume deploying to Heroku.

---

I'm closing this issue since there's nothing to do from the buildpack side, but feel free to hit up the [Vapor Discord server](https://vapor.team) to discuss it further.
