### ISSUE TITLE
Support for Heroku-20 stack

### ISSUE THREAD

**Issue by fvvliet** [vapor-community/heroku-buildpack#55]
I'm trying to update my Vapor API on Heroku from -16 to -20 but get errors as mentioned below. Heroku-support tells me it might be caused by this buildpack. Can this buildpack be updated to support Heroku-20 ? 

Thanks in advance, Frank

`remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Swift app detected
remote: -----> Using Swift 4.0 (from .swift-version file)
remote: -----> Installing clang 7.0.1
remote: xz: (stdin): File format not recognized
remote: ! Push rejected, failed to compile Swift app.
remote:
remote: ! Push failed
remote: Verifying deploy...
remote:
remote: ! Push rejected to VaporAPI`

**Comment by vzsg** [comment]
I'll look into whether there's anything blocking the buildpack from being used on heroku-20.

But your project is unlikely to work either way, as it is now. Swift 4.0, the version you have pinned in .swift-version, is very old. Not counting the tons of bugs that have been fixed since then, it also didn't support Ubuntu 20.04 – that support only appeared in Swift 5.2.4.

So please try pinning a newer version of Swift in the meantime. I think 5.3.1 will work immediately.
(As I also need to fix support for 5.3.2.)

**Comment by vzsg** [comment]
Update: the buildpack now supports the heroku-20 stack for all supported Swift versions, and will tell you if your project has an unsupported configuration.

I'm closing this issue as what I could do on the buildpack side is done, but let me know if you run into trouble with the upgrade.

**Comment by fvvliet** [comment]
Thanks fo your help. Indeed I can't get the old code (Vapor 2) to work anymore, have to upgrade...
